-- -------------------------------------------------------------
-- TablePlus 4.5.2(402)
--
-- https://tableplus.com/
--
-- Database: isi
-- Generation Time: 2022-01-20 15:12:44.2360
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE TABLE `account` (
  `ACCID` varchar(255) NOT NULL DEFAULT '' COMMENT 'Account ID',
  `ACCNAME` varchar(255) NOT NULL COMMENT 'Username',
  `HASHEDPASSWORD` varchar(255) NOT NULL COMMENT 'Encrypted user password',
  `EMAIL` varchar(255) NOT NULL COMMENT 'User E-mail',
  `ACCTYPE` varchar(255) NOT NULL DEFAULT 'customer' COMMENT 'Account Type: (admin, user, vendor)',
  PRIMARY KEY (`ACCID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `address` (
  `ADDID` varchar(255) NOT NULL DEFAULT '' COMMENT 'Address ID',
  `TEL` varchar(255) NOT NULL COMMENT 'Telephone number',
  `NAME` varchar(255) NOT NULL COMMENT 'Customer full name',
  `CITY` varchar(255) NOT NULL COMMENT 'City',
  `COUNTRY` varchar(255) NOT NULL COMMENT 'Country or region',
  `DETAILED` varchar(255) NOT NULL COMMENT 'Detailed address',
  `ACCID` varchar(255) NOT NULL COMMENT 'Account ID',
  PRIMARY KEY (`ADDID`),
  KEY `ACCID` (`ACCID`),
  CONSTRAINT `address_ibfk_2` FOREIGN KEY (`ACCID`) REFERENCES `account` (`ACCID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order` (
  `PONO` varchar(255) NOT NULL DEFAULT '' COMMENT 'Purchase ID',
  `PRICE` double NOT NULL DEFAULT 0 COMMENT 'Product sales price',
  `OID` varchar(255) NOT NULL COMMENT 'Order ID',
  `PID` varchar(255) NOT NULL COMMENT 'Product ID',
  PRIMARY KEY (`OID`),
  KEY `PONO` (`PONO`),
  KEY `PID` (`PID`),
  CONSTRAINT `order_ibfk_1` FOREIGN KEY (`PONO`) REFERENCES `purchase` (`PONO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `order_ibfk_2` FOREIGN KEY (`PID`) REFERENCES `product` (`PID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `product` (
  `PID` varchar(255) NOT NULL COMMENT 'Product ID',
  `PNAME` varchar(255) NOT NULL COMMENT 'Product Name',
  `BRAND` varchar(255) NOT NULL COMMENT 'Brand',
  `PRICE` double NOT NULL COMMENT 'Sales price',
  `PDESC` text NOT NULL COMMENT 'Description',
  `THUMBNAIL` varchar(255) NOT NULL COMMENT 'Tumbnail Image',
  `PIC` text NOT NULL COMMENT 'Images',
  `CATALOG` varchar(255) NOT NULL COMMENT 'Product catalogue',
  PRIMARY KEY (`PID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `purchase` (
  `PONO` varchar(255) NOT NULL DEFAULT '' COMMENT 'Purchase ID',
  `ACCID` varchar(255) NOT NULL DEFAULT '' COMMENT 'Account ID',
  `DATE` date NOT NULL DEFAULT current_timestamp() COMMENT 'Purchase generated date',
  `STATUS` varchar(255) NOT NULL DEFAULT 'pending' COMMENT 'Purchase status',
  PRIMARY KEY (`PONO`),
  KEY `ACCID` (`ACCID`),
  CONSTRAINT `purchase_ibfk_1` FOREIGN KEY (`ACCID`) REFERENCES `account` (`ACCID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `shopping_cart` (
  `ACCID` varchar(255) NOT NULL DEFAULT '' COMMENT 'Account ID',
  `PID` varchar(255) NOT NULL DEFAULT '' COMMENT 'Product ID',
  `QUANTITY` int(11) NOT NULL DEFAULT 1 COMMENT 'Quantity of product',
  `CARTID` varchar(255) NOT NULL COMMENT 'Shopping Cart ID',
  PRIMARY KEY (`CARTID`),
  KEY `ACCID` (`ACCID`),
  KEY `PID` (`PID`),
  CONSTRAINT `shopping_cart_ibfk_1` FOREIGN KEY (`ACCID`) REFERENCES `account` (`ACCID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `shopping_cart_ibfk_2` FOREIGN KEY (`PID`) REFERENCES `product` (`PID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;