-- -------------------------------------------------------------
-- TablePlus 4.5.2(402)
--
-- https://tableplus.com/
--
-- Database: isi
-- Generation Time: 2022-01-19 21:37:35.5670
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE TABLE `account` (
  `ACCID` varchar(255) NOT NULL DEFAULT '',
  `ACCNAME` varchar(255) NOT NULL,
  `HASHEDPASSWORD` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `ACCTYPE` varchar(255) NOT NULL DEFAULT 'customer',
  PRIMARY KEY (`ACCID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `address` (
  `ADDID` varchar(255) NOT NULL DEFAULT '',
  `TEL` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `CITY` varchar(255) NOT NULL,
  `COUNTRY` varchar(255) NOT NULL,
  `DETAILED` varchar(255) NOT NULL,
  `ACCID` varchar(255) NOT NULL,
  PRIMARY KEY (`ADDID`),
  KEY `ACCID` (`ACCID`),
  CONSTRAINT `address_ibfk_2` FOREIGN KEY (`ACCID`) REFERENCES `account` (`ACCID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `order` (
  `PONO` varchar(255) NOT NULL DEFAULT '',
  `PRICE` double NOT NULL DEFAULT 0,
  `OID` varchar(255) NOT NULL,
  `PID` varchar(255) NOT NULL,
  PRIMARY KEY (`OID`),
  KEY `PONO` (`PONO`),
  KEY `PID` (`PID`),
  CONSTRAINT `order_ibfk_1` FOREIGN KEY (`PONO`) REFERENCES `purchase` (`PONO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `order_ibfk_2` FOREIGN KEY (`PID`) REFERENCES `product` (`PID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `product` (
  `PID` varchar(255) NOT NULL,
  `PNAME` varchar(255) NOT NULL,
  `BRAND` varchar(255) NOT NULL,
  `PRICE` double NOT NULL,
  `PDESC` text NOT NULL,
  `THU` varchar(255) NOT NULL,
  `PIC` text NOT NULL,
  `CATALOG` varchar(255) NOT NULL,
  PRIMARY KEY (`PID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `purchase` (
  `PONO` varchar(255) NOT NULL DEFAULT '',
  `ACCID` varchar(255) NOT NULL DEFAULT '',
  `DATE` date NOT NULL DEFAULT current_timestamp(),
  `STATUS` varchar(255) NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`PONO`),
  KEY `ACCID` (`ACCID`),
  CONSTRAINT `purchase_ibfk_1` FOREIGN KEY (`ACCID`) REFERENCES `account` (`ACCID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `shopping_cart` (
  `ACCID` varchar(255) NOT NULL DEFAULT '',
  `PID` varchar(255) NOT NULL DEFAULT '',
  `QUANTITY` int(11) NOT NULL DEFAULT 1,
  `CARTID` varchar(255) NOT NULL,
  PRIMARY KEY (`CARTID`),
  KEY `ACCID` (`ACCID`),
  KEY `PID` (`PID`),
  CONSTRAINT `shopping_cart_ibfk_1` FOREIGN KEY (`ACCID`) REFERENCES `account` (`ACCID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `shopping_cart_ibfk_2` FOREIGN KEY (`PID`) REFERENCES `product` (`PID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;